### ISSUE TITLE
Support arbitrary CalDAV servers

### ISSUE THREAD

**Issue by paulmueller** [ubports/calendar-app#2] opened 2017-06-21 20:17 UTC
Currently, the Calendar app only supports OwnCloud and Google calendars. I am managing my calendars with [radicale](http://radicale.org/) and would like to be able to sync it from within the app. As a workaround, I use a cron job with syncevolution, but I this creates uncontrollable traffic and probably causes the battery to drain.

**Comment by NeoTheThird** [comment] 2017-07-14 17:26
There's a [bounty on this](https://www.bountysource.com/issues/30551831-no-caldav-and-icalendar-support).

**Comment by seteahconnoc** [comment] 2017-07-24 23:25
Any advance in this issue would be quite helpful. I am using a caldav calendar at "posteo.de" and would appreciate simple support for UBports very much.

**Comment by NeoTheThird** [comment] 2017-07-25 10:10
I think @lkristensen is working on this, but i'm not sure what the status is.

**Comment by lkristensen** [comment] 2017-07-26 00:00
I am working on this. Support for CalDav actually is not taking place in the Calendar app, but in the SyncMonitor daemon. I am working on setting up proper testing framework and when I have it up and running it should be fairly simple to implement. Finale step will then be to understand how to replace the SyncMonitor daemon, I do not have a good understanding of that yet.

**Comment by seteahconnoc** [comment] 2017-07-26 06:41
That sounds promising. Thanks for the insights in the background of this problem.

For me as a simple user, there is the question, if I would find (someday) a beta version of the app in the "Open Store". Or do I have to check out `https://github.com/lkristensen/calendar-app`?

**Comment by lkristensen** [comment] 2017-07-26 06:59
Unfortunately it will be a bit more involved. Because the apps have been created with security in mind, the syncrhonisation (caldav etc) part of the software cannot be installed as an app, but when we get to the beta stage, I will make sure to share the installation instructions so that you will have a chance to test it.

**Comment by seteahconnoc** [comment] 2017-07-26 13:12
Excuse me, but I have to ask again: How to I get to know, if there would be something to test in a beta stage? Do you leave a "problem solved" message right here in this github thread?

It would be quite helpful for me, if the installation procedure would not require too much expertise. I would be happy to give you feedback from the perspective of a potential "end user".

**Comment by NeoTheThird** [comment] 2017-07-26 14:53
@seteahconnoc We will figure something out about that, for now, the only way of trying out the latest and greatest, would be to download this repository, build it yourself and installing the click package on your device, but since no work has gotten into this issue yet, your best bet would be to just set up cal dav syncing with [the old method](https://gist.github.com/tcarrondo/c932750928c83310fd84f8376ee17f30).

**Comment by seteahconnoc** [comment] 2017-07-26 17:27
@NeoTheThird Thanks. So, right now there is simply no way to achieve the functionality out of the box. As said: It would be nice to get an update, if there 's progress for the "end user".

In order to use the mentioned old method, I need a quick tutorial in starting scripts on my phone. Where do I put the file? How do I start it? What do I have to keep in mind? Basically: some "hello_world.sh" stuff. It would be nice, if you can give me some "dummy advice" in this topic.

**Comment by seteahconnoc** [comment] 2017-07-28 19:17
I tried out `tcarrondo`'s script `syncevolution_generic_caldav.sh` today. It 's all working just fine. Yet, I would be happy to see a calendar app with advanced functionality someday.

**Comment by seteahconnoc** [comment] 2017-09-25 11:02
I upgrades my UBports system with "Ubuntu Touch 15.04 OTA-2": The calendar can now sync with generic CalDAV servers. So, it 's just working out of the box.

**Comment by bobblkabb** [comment] 2017-09-25 11:07
Didn't work for me propably because my server's https.

**Comment by seteahconnoc** [comment] 2017-09-25 11:14
@bobblkabb I 'm using a calendar at "posteo.de". Here 's the general configuration for Lightning:
https://posteo.de/en/help/how-do-i-set-up-synchronisation-of-calendar-entries-with-the-thunderbird-calendar
As you see, it 's using "https". So, your problem might have it 's origin somewhere else.

**Comment by bobblkabb** [comment] 2017-09-25 11:25
Maybe because it's a selfsigned ssl certificate?!
How can I find out where the problem is?

**Comment by paulmueller** [comment] 2017-09-25 11:33
@bobblkabb You probably have to copy the servers public certificate file (must have .crt extension) to "/usr/local/share/ca-certificates/" and run `sudo update-ca-certificates`. Your system image must be writable, which you can achieve using e.g. "UT Teak Tool" from the OpenStore.

**Comment by bobblkabb** [comment] 2017-09-25 18:04
Generic calendar accepts my nextcloud calendar but it doesn't show it neither the calendar itself nor the entries. Thoug when I snyc it is recognized but still nothing's shown.

**Comment by NeoTheThird** [comment] 2017-10-02 11:56
Sorry guys, i forgot to close this. As @seteahconnoc said, this has been fixed by @mardy in ubports/sync-monitor#1 and #19 and published in OTA-2. If you're experiencing issues with this, please report them seperately. Thanks :)

**Closed by NeoTheThird** 2017-10-02 11:56 UTC
Labels: bounty, enhancement, help wanted
