### ISSUE TITLE
Cannot switch default calendar

### ISSUE THREAD

**Issue by neopar** [ubports/calendar-app#129] opened 2018-10-25 09:14 UTC
- BQ E5
- OTA-5 
- Calendar v 0.7.2

Steps to reproduce:
1. Add caldav account
2. Set it as default
3. Add another caldav account
4. Set the new one as defalt
5. Close settings
6. Open settings - default account is set the first one agian.

**Comment by hummlbach** [comment] 2018-10-25 23:13
Confirmed.

**Comment by mardy** [comment] 2018-10-26 10:15
Duplicate of ubports/ubuntu-touch#919

**Closed by mardy** 2018-10-26 10:15 UTC
Labels: bug
