### ISSUE TITLE
Default calendar cannot be changed

### ISSUE THREAD

**Issue by wagafo** [ubports/calendar-app#126] opened 2018-10-20 16:20 UTC
16.04 - Stable channel

What happens?
In Settings -> Default calendar, I always see the first calendar in the list as the default calendar. If I want to change the default calendar to any of the other calendars in the list, once I close Settings and open it again, the first calendar is again the default one. 

What should happen?
One should be able to define any of the calendars of the list as default.

I don't know if it is related to the fact that these are Google calendars that come from my Google account.

**Comment by mardy** [comment] 2018-10-24 06:36
Duplicate of https://github.com/ubports/ubuntu-touch/issues/919

**Closed by mardy** 2018-10-24 06:36 UTC
